### ISSUE TITLE
Merklik László - Jobb minőséget tesztelők nélkül

### ISSUE THREAD

**Issue by presidento** [balabit/coderegation#56]
speaker: Merklik László
topic: Jobb minőséget tesztelők nélkül (HU)
video: https://www.youtube.com/watch?v=fVmRkMiWEpE
length: 45 min

Elsőre talán furcsa a felvetés. Ha másodikra is az, akkor mindenképpen nézd meg az előadást, és megtudod, hogyan és miért számoltuk fel a manuális tesztelői szerepet, illetve hogy mi lett ennek az eredménye.

**Comment by attilammagyar** [comment]
+1

**Comment by bkil-syslogng** [comment]
I was there on this [meetup](http://www.meetup.com/Craft-meetup/events/229120436/) and it was awesome (maybe you can find me in the corner if you watch closely). Both the place and the presentation was good. He made a great joke about the `death of the tester` in the break as well.

I especially like their slide style and intended to send a photo to fun@ about it, but never had the time to do that.

EDIT: By the way, it was on Wednesday at almost this time, and probably I couldn't come to a coderegation because of that. Why aren't you coming to the meetups directly to enjoy the live show, great people and good catering instead of time shifting it to a very similar spot?

**Comment by bkil-syslogng** [comment]
What about the second part?
https://www.youtube.com/watch?v=1aQPdwuky0k

**Comment by attilammagyar** [comment]
@bkil-syslogng https://github.com/balabit/coderegation/issues/58
