### ISSUE TITLE
Gerard Holzmann - Mars Code

### ISSUE THREAD

**Issue by attilammagyar** [balabit/coderegation#62]
speaker: Gerard Holzmann
topic: Mars Code
video: https://vimeo.com/84991949
length: 63 min

Gerard Holzmann, senior research scientist at NASA’s Jet Propulsion Laboratory, describes creating the software for the Curiosity rover in this video accompaniment to “Mars Rover,” his article in the February 2014 Communications of the ACM (cacm.acm.org/magazines/2014/2/171689).

**Comment by bkil-syslogng** [comment]
:+1: :v: :heart:

**Comment by attilammagyar** [comment]
Here's the docs: http://lars-lab.jpl.nasa.gov/JPL_Coding_Standard_C.pdf // via @csernazs

**Comment by bkil-syslogng** [comment]
Thanks. Here's a TL;DR table of contents extract:

== Rule Summary ==
1. Language Compliance
   1. Do not stray outside the language definition.
   2. Compile with all warnings enabled; use static source code analyzers.
2. Predictable Execution
   3. Use verifiable loop bounds for all loops meant to be terminating.
   4. Do not use direct or indirect recursion.
   5. Do not use dynamic memory allocation after task initialization.
   6. + Use IPC messages for task communication.
   7. Do not use task delays for task synchronization.
   8. + Explicitly transfer write-permission (ownership) for shared data objects.
   9. Place restrictions on the use of semaphores and locks.
   10. Use memory protection, safety margins, barrier patterns.
   11. Do not use goto, setjmp or longjmp.
   12. Do not use selective value assignments to elements of an enum list.
3. Defensive Coding
   13. Declare data objects at smallest possible level of scope.
   14. Check the return value of non-void functions, or explicitly cast to (void).
   15. Check the validity of values passed to functions.
   16. Use static and dynamic assertions as sanity checks.
   17. + Use U32, I16, etc instead of predefined C data types such as int, short, etc.
   18. Make the order of evaluation in compound expressions explicit.
   19. Do not use expressions with side effects.
4. Code Clarity
   20. Make only very limited use of the C pre-processor.
   21. Do not define macros within a function or a block.
   22. Do not undefine or redefine macros.
   23. Place #else, #elif, and #endif in the same file as the matching #if or #ifdef.
   24. + Place no more than one statement or declaration per line of text.
   25. + Use short functions with a limited number of parameters.
   26. + Use no more than two levels of indirection per declaration.
   27. + Use no more than two levels of dereferencing per object reference.
   28. + Do not hide dereference operations inside macros or typedefs.
   29. + Do not use non-constant function pointers.
   30. Do not cast function pointers into other types.
   31. Do not place code or declarations before an #include directive.
5. MISRA shall compliance (All MISRA *shall* rules not already covered at Levels 1-4.)
6. MISRA should compliance (All MISRA *should* rules not already covered at Levels 1-4.)

**Comment by bkil-syslogng** [comment]
Here's a missing link:
* http://caxapa.ru/thumbs/468328/misra-c-2004.pdf
* https://en.wikipedia.org/wiki/MISRA_C#Criticism
